export interface IPersonResult {
  object: string
  count: number
  results: number
  results_per_page: number
  pages: number
  page: number
  offset: number
  has_more: boolean
  data: IPerson[]
}

export interface IPerson {
  object: string
  id: number
  first_name: string
  last_name: string
  middle_name: string
  prefix: null
  suffix: null
  preferred_name: null
  display_name: string
  gender: string
  other_gender: null
  image_file_id: null
  birth_date: null
  status: string
  social_security_number: null
  alien_registration_number: null
  social_insurance_number: null
  home_city: null
  home_state: null
  home_country: null
  former_name: null
  license_plate: null
  bio: null
  hispanic_latino: boolean
  resident_alien: boolean
  localization_id: null
  notification_email_id: null
  deceased_date: null
  import_id: null
  added_at: null
  added_by_id: null
  updated_at: null
  report_data: ReportData
  private_profile: boolean
  is_user: boolean
}

interface ReportData {
  person_id: number
  active_roles: null
  username: null
  primary_address_street: null
  primary_address_city: null
  primary_address_state: null
  primary_address_country: null
  is_alum: number
  primary_org_title: null
  primary_org_name: null
  contact_primary_email: null
  contact_primary_phone: null
  visible_student_id: string
}

export interface IPersonFull {
  object: string
  id: number
  first_name: string
  last_name: string
  middle_name: string
  prefix: string
  suffix: null
  preferred_name: null
  display_name: string
  gender: string
  other_gender: null
  image_file_id: null
  birth_date: null
  status: string
  social_security_number: null
  alien_registration_number: null
  social_insurance_number: null
  home_city: null
  home_state: null
  home_country: null
  former_name: null
  license_plate: null
  bio: null
  hispanic_latino: boolean
  resident_alien: boolean
  localization_id: null
  notification_email_id: null
  deceased_date: null
  import_id: null
  addresses: Address[]
  tags: IPopuliTag[]
  added_at: null
  added_by_id: null
  updated_at: Date
  private_profile: boolean
  is_user: boolean
  sandbox: boolean
}

interface Address {
  object: string
  id: number
  owner_id: number
  owner_type: string
  street: string
  city: string
  state: string
  postal: string
  country: string
  type: string
  primary: boolean
  old: boolean
  public: boolean
  synced_from: null
  import_id: null
  added_at: null
  added_by_id: number
}

export interface IPopuliTag {
  object: string
  id: number
  name: string
  autogenerated: null
  added_at: null
  added_by_id: null
}
