// Generated by https://quicktype.io

export interface IPopuliPeopleResponse {
  object: string
  count: number
  results: number
  results_per_page: number
  pages: number
  page: number
  offset: number
  has_more: boolean
  data: IPopuliPerson[]
}

export interface IPopuliPerson {
  object: OwnerTypeEnum
  id: number
  first_name: string
  last_name: string
  middle_name: string
  prefix: null
  suffix: null
  preferred_name: null | string
  display_name: string
  gender: Gender | null
  other_gender: null
  raceid: number
  image_file_id: number | null
  birth_date: null | string
  status: Status
  alien_registration_number: null
  home_city: null
  home_state: null
  home_country: null
  former_name: null | string
  license_plate: null
  bio: null
  updated_at: string
  hispanic_latino: boolean
  resident_alien: boolean
  localization_id: null
  notification_email_id: null
  deceased_date: null
  added_by_id: number
  added_at: string
  import_id: null
  report_data: ReportData
  email_addresses: EmailAddress[]
  tags: Tag[]
  private_profile: boolean
  is_user: boolean
}

interface Address {
  object: PurpleObject
  id: number
  owner_id: number
  owner_type: OwnerTypeEnum
  street: string
  city: string
  state: null | string
  postal: null | string
  country: string
  type: Type
  primary: boolean
  old: boolean
  public: boolean
  synced_from: null
  added_by_id: number
  added_at: string
  import_id: null
}

enum PurpleObject {
  Address = "address",
}

enum OwnerTypeEnum {
  Person = "person",
}

enum Type {
  Billing = "billing",
  Home = "home",
  Other = "other",
  School = "school",
  Shipping = "shipping",
  Work = "work",
}

interface EmailAddress {
  object: FluffyObject
  id: number
  owner_id: number
  owner_type: OwnerTypeEnum
  email: string
  type: Type
  primary: boolean
  old: boolean
  system: boolean
  public: boolean
  synced_from: null
  delivery_problem: null | string
  delivery_problem_at: null | string
  delivery_problem_info: null | string
  verified_at: null | string
  added_by_id: number
  added_at: string
  import_id: null
}

enum FluffyObject {
  EmailAddress = "email_address",
}

enum Gender {
  Female = "female",
  Male = "male",
}

interface ReportData {
  person_id: number
  active_roles: null | string
  username: null | string
  primary_address_street: null | string
  primary_address_city: null | string
  primary_address_state: null | string
  primary_address_country: null | string
  is_alum: number
  primary_org_title: null | string
  primary_org_name: null | string
  contact_primary_email: null | string
  contact_primary_phone: null | string
  visible_student_id: null | string
}

enum Status {
  Active = "active",
}

interface Tag {
  object: TagObject
  id: number
  name: string
  autogenerated: number | null
  added_by_id: number | null
  added_at: null | string
  person_id: number
}

enum TagObject {
  Tag = "tag",
}
